---
# proxmox and proxmox_kvm options
api_user: 'root@pam'
api_password: '{{ vault_api_password }}'
api_host: 'pve.home'
defaults:
  cores: '1'
  cpu: '1'
  memory:
    ct: '1024'
  onboot: true
  node: 'pve'
  pubkey: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  disk: '8'
  nameserver: '192.168.1.31'
  storage:
    ct: 'local-lvm'
  ostemplate: 'local:vztmpl/ubuntu-22.04-standard_22.04-1_amd64.tar.zst'

cts:
  grafana:
    vmid: 208
    password: "{{ vault_default_password }}"
    
  
